---
title: "purrr example_1"
author: "Kinare, Mayuresh"
date: "5/5/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, echo=TRUE}
#sourcing dependencies
source('/mnt/d/gitRepoCheckout/purrr_testing/dependencies_library.R')
source('/mnt/d/gitRepoCheckout/purrr_testing/dependencies_download_unzip.R')

```

```{r cache=FALSE, echo=FALSE}
knitr::read_chunk('/mnt/d/gitRepoCheckout/purrr_testing/dependencies_library.R')
knitr::read_chunk('/mnt/d/gitRepoCheckout/purrr_testing/dependencies_download_unzip.R')
```

## R Markdown

This is an example from http://data.library.virginia.edu/getting-started-with-the-purrr-package-in-r/


Obtaining a list of names of the files we want to load
```{r, echo=TRUE}

# get all files ending in csv
files <- list.files(pattern = "csv$") 

```


Loading csv files using lapply 
```{r, echo=TRUE}
# read in data normally
dat <- lapply(files, read.csv)
names(dat) <- gsub("\\.csv", "", files) # remove file extension

```

Loading csv files using purrr 
```{r, echo=TRUE}

# read in data using purrr
dat2 <- map(files, read.csv)
names(dat2) <- gsub("\\.csv", "", files)

```

Computation using lapply
```{r, echo=TRUE}
#want to find the mean Open price for each stock. Here is a base R way using lapply and an anonymous function:
  
lapply(dat, function(x)mean(x$Open))

```
Computation using purrr
```{r, echo=TRUE}
#want to find the mean Open price for each stock.
  
map(dat, function(x)mean(x$Open))

```
